name: Master Branch CI

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: Unit & Integration Tests
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B verify --file pom.xml
        working-directory: moviebuffs-api

  sonar:
    name: Test - SonarCloud Scan
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: SonarCloud Scan
        run: mvn -B clean verify -Pci -Dsonar.login=${{ secrets.SONAR_TOKEN }}
        working-directory: moviebuffs-api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
